name: Deploy DVWA to ROSA

on:
  push:
    branches: [ master, main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push DVWA Image
        env:
          ECR_REGISTRY: 273434037588.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: dvwa-repo
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # ADD WIZ CLI SCANNING HERE
      - name: Download Wiz CLI
        run: |
          curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64
          chmod +x wizcli

      - name: Authenticate Wiz CLI
        run: |
          ./wizcli auth --id "${{ secrets.WIZ_CLIENT_ID }}" --secret "${{ secrets.WIZ_CLIENT_SECRET }}"

      - name: Scan Image with Wiz CLI
        run: |
          ./wizcli docker scan --image 273434037588.dkr.ecr.us-east-1.amazonaws.com/dvwa-repo:latest --policy-hits-only --policy "Image Trust Policy"

      - name: OpenShift Login
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.dvwa-rosa.nym5.p3.openshiftapps.com:443
          openshift_token: ${{ secrets.ROSA_TOKEN }}
          insecure_skip_tls_verify: true

      - name: Deploy to ROSA
        run: |
          oc project dvwa-prod || oc new-project dvwa-prod
          oc new-app --name=dvwa \
            --docker-image=273434037588.dkr.ecr.us-east-1.amazonaws.com/dvwa-repo:latest \
            --confirm || \
          oc set image deployment/dvwa dvwa=273434037588.dkr.ecr.us-east-1.amazonaws.com/dvwa-repo:latest
          oc expose svc/dvwa || echo "Route already exists"
          oc rollout restart deployment/dvwa
          echo "DVWA is live at: http://$(oc get route dvwa -n dvwa-prod -o jsonpath='{.spec.host}')"
